PREFIX schema: <https://schema.org/>

# Select all art periods, assigned to heritage objects or not
SELECT *
WHERE {
  ?artPeriod a schema:DefinedTerm ;
    schema:name ?name .
  OPTIONAL { ?artPeriod schema:startDate ?startDate }
  OPTIONAL { ?artPeriod schema:endDate ?endDate }
}
ORDER BY ?startDate
LIMIT 10000
