PREFIX schema: <https://schema.org/>

# Select the heritage object's details
SELECT *
WHERE {
  BIND(<http://data.collectienederland.nl/resource/document/mauritshuis/264> AS ?heritageObject)

  ?heritageObject a schema:VisualArtwork ;
    schema:name ?name ;
    schema:description ?description ;
    schema:temporalCoverage ?temporalCoverage ;
    schema:dateCreated ?dateCreated ;
    schema:image ?image ;
    schema:creator ?creator ;
    schema:publisher ?publisher .

  OPTIONAL { ?heritageObject schema:mainEntityOfPage ?webpage }

  # Art period
  ?temporalCoverage schema:name ?artPeriodName ;
    schema:startDate ?artPeriodStartDate ;
    schema:endDate ?artPeriodEndDate .

  # Image
  ?image schema:contentUrl ?imageContentUrl ;
    schema:license ?imageLicense . # TBD: also add name of the license?
  OPTIONAL { ?image schema:encodingFormat ?imageEncodingFormat }

  # Creator
  ?creator <http://schema.org/name> ?creatorName .

  # Publisher
  ?publisher schema:name ?publisherName ;
    schema:mainEntityOfPage ?publisherHomepage .
}
