PREFIX schema: <https://schema.org/>

# Select the heritage object's details
SELECT *
WHERE {
  BIND(<http://data.collectienederland.nl/resource/document/mauritshuis/264> AS ?heritageObject)

  ?heritageObject a schema:VisualArtwork ;
    schema:name ?name ;
    schema:description ?description ;
    schema:dateCreated ?dateCreated ;
  OPTIONAL { ?heritageObject schema:mainEntityOfPage ?webpage }

  # Art period
  ?heritageObject schema:temporalCoverage/schema:name ?artPeriodName ;
    schema:temporalCoverage/schema:startDate ?artPeriodStartDate ;
    schema:temporalCoverage/schema:endDate ?artPeriodEndDate .

  # Image
  ?heritageObject schema:image ?image .
  ?image schema:contentUrl ?imageContentUrl ;
    schema:license ?imageLicense . # TBD: also add name of the license?
  OPTIONAL { ?image schema:encodingFormat ?imageEncodingFormat }

  # Creator
  ?heritageObject schema:creator/<http://schema.org/name> ?creatorName .

  # Publisher
  ?heritageObject schema:publisher/schema:name ?publisherName .
  OPTIONAL { ?heritageObject schema:publisher/schema:mainEntityOfPage ?publisherHomepage }
}
