PREFIX schema: <https://schema.org/>

# Use a 'scrollable cursor' - https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksHowToHandleBandwidthLimitExceed
SELECT *
WHERE {
  {
    SELECT *
    WHERE {
      BIND(<http://vocab.getty.edu/aat/300021147> AS ?temporalCoverage) # 'Barok' - for testing

      ?heritageObject a schema:VisualArtwork ;
        schema:name ?name ;
        schema:dateCreated ?dateCreated ;
        schema:creator ?creator ;
        schema:temporalCoverage ?temporalCoverage ;
        schema:image ?image .

      # Image
      ?image schema:contentUrl ?imageContentUrl ;
        schema:license ?imageLicense . # TBD: also add name of the license?
      OPTIONAL { ?image schema:encodingFormat ?imageEncodingFormat }

      # Creator
      ?creator <http://schema.org/name> ?creatorName .
    }
    ORDER BY ?dateCreated
  }
}
LIMIT 1000
OFFSET 0 # For pagination
