PREFIX gn: <http://www.geonames.org/ontology#>

# Generate a mini graph with GeoNames' locations
CONSTRUCT {
  ?uri a gn:Feature ;
    gn:name ?name ;
    gn:featureCode ?featureCode ;
    gn:parentADM1 ?admin1GeonamesUri ;
    gn:parentCountry <https://sws.geonames.org/2750405/> . # "Nederland"
}
WHERE {
  BIND(URI(CONCAT('https://sws.geonames.org/', ?geonamesId, '/')) AS ?uri)
  BIND(URI(CONCAT('https://sws.geonames.org/', ?admin1GeonamesId, '/')) AS ?admin1GeonamesUri)
}
