PREFIX schema: <https://schema.org/>

SELECT *
WHERE {
  {
    SELECT *
    WHERE {
      ?heritageObject a schema:VisualArtwork ;
        schema:name ?name ;
        schema:dateCreated ?dateCreated ;
        schema:image ?image .
      ?image schema:contentUrl ?imageContentUrl ;
        schema:license ?imageLicense . # TBD: also add name of the license?
      OPTIONAL { ?image schema:encodingFormat ?imageEncodingFormat }
      ?heritageObject schema:creator/<http://schema.org/name> ?creatorName ;
        schema:temporalCoverage <http://vocab.getty.edu/aat/300021147> . # 'Barok'
    }
    ORDER BY ?dateCreated
  }
}
LIMIT 1000
OFFSET 0 # For pagination
